# Generated by Django 5.2 on 2026-03-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фотография/изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Секция "Обо мне"',
                'verbose_name_plural': 'Секция "Обо мне"',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (username)')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Секция контактов',
                'verbose_name_plural': 'Секция контактов',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение')),
                ('cta_text', models.CharField(default='Узнать больше', max_length=100, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(default='#skills', max_length=100, verbose_name='Ссылка кнопки (якорь)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Hero секция',
                'verbose_name_plural': 'Hero секция',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Портфолио', max_length=200, verbose_name='Название сайта')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фавикон')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Вторичный цвет')),
                ('custom_css', models.TextField(blank=True, verbose_name='Кастомный CSS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='CSS класс иконки (FontAwesome)')),
            ],
            options={
                'verbose_name': 'Категория навыков',
                'verbose_name_plural': 'Категории навыков',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='URL (якорь)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.navigationitem', verbose_name='Родительский пункт (для выпадающего меню)')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Изображение/Иконка')),
                ('proficiency', models.IntegerField(default=80, help_text='0-100', verbose_name='Уровень владения (%)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в категории')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать в featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
